engines:
  eslint:
    enabled: true
    channel: "eslint-2"
    config:
      config: .eslintrc
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
   paths:
   - "**.js"
